-- 007: repository detail pages — slug, category, cover, 4-language summaries
ALTER TABLE repository_items ADD COLUMN slug TEXT;
ALTER TABLE repository_items ADD COLUMN category TEXT;
ALTER TABLE repository_items ADD COLUMN cover_image_key TEXT;
ALTER TABLE repository_items ADD COLUMN summary_en TEXT;
ALTER TABLE repository_items ADD COLUMN summary_nl TEXT;
ALTER TABLE repository_items ADD COLUMN summary_de TEXT;
ALTER TABLE repository_items ADD COLUMN summary_fr TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS idx_repo_slug ON repository_items(slug);
UPDATE repository_items SET slug='cmr-convention-1956', category='convention',
  cover_image_key='marketing/covers/repo-cmr-convention-1956.jpg',
  summary_en='The CMR Convention (Geneva, 1956) governs the contract of carriage for international road transport of goods. It standardises the consignment note, fixes the carrier''s liability between takeover and delivery (with a compensation cap per kilogram), and sets strict claim and limitation periods. It applies automatically whenever the place of takeover and the place of delivery are in two different countries of which at least one is a CMR party, regardless of what the contract says.', summary_nl='Het CMR-verdrag (Genève, 1956) regelt de vervoerovereenkomst voor internationaal goederenvervoer over de weg. Het standaardiseert de vrachtbrief, legt de aansprakelijkheid van de vervoerder vast tussen inontvangstneming en aflevering (met een schadevergoedingslimiet per kilogram) en bepaalt strikte klacht- en verjaringstermijnen. Het verdrag geldt automatisch zodra laad- en losplaats in twee verschillende landen liggen waarvan er minstens één partij is bij het CMR.',
  summary_de='Das CMR-Übereinkommen (Genf, 1956) regelt den Beförderungsvertrag im internationalen Straßengüterverkehr. Es standardisiert den Frachtbrief, legt die Haftung des Frachtführers zwischen Übernahme und Ablieferung fest (mit einer Entschädigungsgrenze je Kilogramm) und bestimmt strenge Reklamations- und Verjährungsfristen. Es gilt automatisch, sobald Übernahme- und Ablieferungsort in zwei verschiedenen Staaten liegen, von denen mindestens einer Vertragspartei ist.', summary_fr='La Convention CMR (Genève, 1956) régit le contrat de transport international de marchandises par route. Elle normalise la lettre de voiture, fixe la responsabilité du transporteur entre la prise en charge et la livraison (avec un plafond d''indemnisation par kilogramme) et impose des délais stricts de réclamation et de prescription. Elle s''applique automatiquement dès que les lieux de prise en charge et de livraison se trouvent dans deux pays différents dont au moins un est partie à la CMR.',
  updated_at=unixepoch()
WHERE title='CMR Convention (1956)';
UPDATE repository_items SET slug='ecmr-protocol-2008', category='protocol',
  cover_image_key='marketing/covers/repo-ecmr-protocol-2008.jpg',
  summary_en='The Additional Protocol to the CMR (2008) gives the electronic consignment note (e-CMR) the same legal force as the paper document. Parties may issue, sign and exchange the consignment note by reliable electronic means, provided integrity and authenticity are guaranteed. It is the legal foundation for paperless road transport documents across the countries that have ratified it.', summary_nl='Het Aanvullend Protocol bij het CMR (2008) geeft de elektronische vrachtbrief (e-CMR) dezelfde rechtskracht als het papieren document. Partijen mogen de vrachtbrief elektronisch opmaken, ondertekenen en uitwisselen, mits integriteit en authenticiteit gewaarborgd zijn. Het is de juridische basis voor papierloos wegvervoer in de landen die het protocol hebben geratificeerd.',
  summary_de='Das Zusatzprotokoll zum CMR (2008) verleiht dem elektronischen Frachtbrief (e-CMR) dieselbe Rechtskraft wie dem Papierdokument. Die Parteien dürfen den Frachtbrief elektronisch ausstellen, unterzeichnen und austauschen, sofern Integrität und Authentizität gewährleistet sind. Es ist die rechtliche Grundlage für papierlose Transportdokumente in den Staaten, die es ratifiziert haben.', summary_fr='Le Protocole additionnel à la CMR (2008) confère à la lettre de voiture électronique (e-CMR) la même valeur juridique que le document papier. Les parties peuvent établir, signer et échanger la lettre de voiture par voie électronique fiable, à condition d''en garantir l''intégrité et l''authenticité. C''est le fondement juridique du transport routier sans papier dans les pays l''ayant ratifié.',
  updated_at=unixepoch()
WHERE title='Additional Protocol e-CMR (2008)';
UPDATE repository_items SET slug='cim-cotif-appendix-b', category='convention',
  cover_image_key='marketing/covers/repo-cim-cotif-appendix-b.jpg',
  summary_en='The CIM Uniform Rules (Appendix B to COTIF) govern the contract of international carriage of goods by rail. They regulate the rail consignment note, the carrier''s liability for loss, damage and transit delay, and the handling of claims. They apply to rail journeys crossing borders between COTIF member states, and increasingly matter for combined road-rail transport in Europe.', summary_nl='De Uniforme Regelen CIM (Aanhangsel B bij COTIF) regelen de overeenkomst voor internationaal goederenvervoer per spoor. Ze bepalen de spoorvrachtbrief, de aansprakelijkheid van de vervoerder bij verlies, schade en vertraging, en de afhandeling van vorderingen. Ze gelden voor grensoverschrijdend spoorvervoer tussen COTIF-lidstaten en worden steeds belangrijker voor gecombineerd weg-spoorvervoer in Europa.',
  summary_de='Die Einheitlichen Rechtsvorschriften CIM (Anhang B zum COTIF) regeln den Vertrag über die internationale Eisenbahnbeförderung von Gütern. Sie bestimmen den Eisenbahnfrachtbrief, die Haftung des Beförderers bei Verlust, Beschädigung und Lieferfristüberschreitung sowie die Geltendmachung von Ansprüchen. Sie gelten für grenzüberschreitende Bahntransporte zwischen COTIF-Mitgliedstaaten und gewinnen im kombinierten Verkehr an Bedeutung.', summary_fr='Les Règles uniformes CIM (Appendice B à la COTIF) régissent le contrat de transport international ferroviaire de marchandises. Elles encadrent la lettre de voiture ferroviaire, la responsabilité du transporteur en cas de perte, d''avarie ou de retard, et le traitement des réclamations. Elles s''appliquent aux transports ferroviaires transfrontaliers entre États membres de la COTIF et comptent de plus en plus pour le transport combiné rail-route.',
  updated_at=unixepoch()
WHERE title='CIM — Appendix B to COTIF';
UPDATE repository_items SET slug='cmni-budapest-2001', category='convention',
  cover_image_key='marketing/covers/repo-cmni-budapest-2001.jpg',
  summary_en='The Budapest Convention (CMNI, 2001) governs the contract for the carriage of goods by inland waterway. It covers the transport document, the carrier''s liability regime including navigational fault defences, and claim periods for barge transport on European rivers and canals such as the Rhine and the Danube.', summary_nl='Het Verdrag van Boedapest (CMNI, 2001) regelt de overeenkomst voor goederenvervoer over de binnenwateren. Het behandelt het vervoerdocument, het aansprakelijkheidsregime van de vervoerder inclusief nautische verweren, en de klachttermijnen voor binnenvaarttransport op Europese rivieren en kanalen zoals de Rijn en de Donau.',
  summary_de='Das Budapester Übereinkommen (CMNI, 2001) regelt den Vertrag über die Güterbeförderung in der Binnenschifffahrt. Es umfasst die Beförderungsurkunde, das Haftungsregime des Frachtführers einschließlich nautischen Verschuldens sowie die Reklamationsfristen für Binnenschiffstransporte auf europäischen Flüssen und Kanälen wie Rhein und Donau.', summary_fr='La Convention de Budapest (CMNI, 2001) régit le contrat de transport de marchandises en navigation intérieure. Elle couvre le document de transport, le régime de responsabilité du transporteur y compris les fautes nautiques, et les délais de réclamation pour le transport fluvial sur les fleuves et canaux européens comme le Rhin et le Danube.',
  updated_at=unixepoch()
WHERE title='CMNI Budapest Convention (2001)';
UPDATE repository_items SET slug='tir-convention-1975', category='handbook',
  cover_image_key='marketing/covers/repo-tir-convention-1975.jpg',
  summary_en='The TIR Convention (1975) is the international customs transit system for goods moving by road across borders under customs seal. With a single TIR carnet and mutual recognition of customs controls, goods can transit multiple countries without repeated border inspections. This 2024 UNECE Handbook edition consolidates the convention text, its annexes and current best practice.', summary_nl='Het TIR-verdrag (1975) is het internationale douanevervoersysteem voor goederen die onder douaneverzegeling over de weg grenzen passeren. Met één TIR-carnet en wederzijdse erkenning van douanecontroles kunnen goederen door meerdere landen reizen zonder herhaalde grensinspecties. Deze UNECE-handboekeditie 2024 bundelt de verdragstekst, de bijlagen en de actuele praktijk.',
  summary_de='Das TIR-Übereinkommen (1975) ist das internationale Zollversandverfahren für Güter, die unter Zollverschluss über Grenzen befördert werden. Mit einem einzigen Carnet TIR und gegenseitiger Anerkennung der Zollkontrollen können Güter mehrere Länder durchqueren, ohne wiederholt kontrolliert zu werden. Diese UNECE-Handbuchausgabe 2024 bündelt Vertragstext, Anlagen und aktuelle Praxis.', summary_fr='La Convention TIR (1975) est le régime international de transit douanier pour les marchandises transportées par route sous scellement douanier. Avec un seul carnet TIR et la reconnaissance mutuelle des contrôles douaniers, les marchandises traversent plusieurs pays sans inspections répétées aux frontières. Cette édition 2024 du manuel CEE-ONU regroupe le texte de la convention, ses annexes et les pratiques actuelles.',
  updated_at=unixepoch()
WHERE title='TIR Convention (1975) — Handbook 2024';
UPDATE repository_items SET slug='efti-regulation-2020-1056', category='regulation',
  cover_image_key='marketing/covers/repo-efti-regulation-2020-1056.jpg',
  summary_en='Regulation (EU) 2020/1056 on electronic freight transport information (eFTI) obliges authorities in all EU member states to accept regulatory freight transport information in electronic form via certified eFTI platforms. It is the EU''s legal backbone for digital transport documents, with full application phasing in through 2027.', summary_nl='Verordening (EU) 2020/1056 over elektronische informatie over goederenvervoer (eFTI) verplicht autoriteiten in alle EU-lidstaten om wettelijke vervoersinformatie elektronisch te accepteren via gecertificeerde eFTI-platforms. Het is de juridische ruggengraat van de EU voor digitale transportdocumenten, met volledige toepassing richting 2027.',
  summary_de='Die Verordnung (EU) 2020/1056 über elektronische Frachtbeförderungsinformationen (eFTI) verpflichtet Behörden in allen EU-Mitgliedstaaten, gesetzliche Beförderungsinformationen elektronisch über zertifizierte eFTI-Plattformen zu akzeptieren. Sie ist das rechtliche Rückgrat der EU für digitale Transportdokumente, mit vollständiger Anwendung bis 2027.', summary_fr='Le règlement (UE) 2020/1056 concernant les informations électroniques relatives au transport de marchandises (eFTI) oblige les autorités de tous les États membres à accepter les informations réglementaires de transport sous forme électronique via des plateformes eFTI certifiées. C''est le socle juridique de l''UE pour les documents de transport numériques, avec une application complète à l''horizon 2027.',
  updated_at=unixepoch()
WHERE title='eFTI Regulation (EU) 2020/1056';
