-- 008: links_json (official sources per item) + 12 new regulatory/reference items
ALTER TABLE repository_items ADD COLUMN links_json TEXT;
UPDATE repository_items SET links_json='[{"label": "Official text EN (UNECE, PDF)", "url": "https://unece.org/fileadmin/DAM/trans/conventn/cmr_e.pdf"}, {"label": "Texte officiel FR (UNECE, PDF)", "url": "https://unece.org/DAM/trans/conventn/cmr_f.pdf"}, {"label": "Ratification status (UN Treaty Collection)", "url": "https://treaties.un.org/pages/ViewDetails.aspx?mtdsg_no=XI-B-11&chapter=11&clang=_en"}]', updated_at=unixepoch() WHERE slug='cmr-convention-1956';
UPDATE repository_items SET links_json='[{"label": "Official text EN (UNECE, PDF)", "url": "https://unece.org/fileadmin/DAM/trans/conventn/e-CMRe.pdf"}, {"label": "Benelux pilot and recognised providers (NIWO)", "url": "https://www.niwo.nl/nl/themas/e-cmr-digitale-vrachtbrief"}]', updated_at=unixepoch() WHERE slug='ecmr-protocol-2008';
UPDATE repository_items SET links_json='[{"label": "Official text (OTIF, PDF)", "url": "https://otif.org/fileadmin/new/3-Reference-Text/3A-COTIF99/05_Appendix_B.pdf"}, {"label": "COTIF reference texts and appendices (OTIF)", "url": "https://otif.org/en/?page_id=53"}]', updated_at=unixepoch() WHERE slug='cim-cotif-appendix-b';
UPDATE repository_items SET links_json='[{"label": "Official text EN (CCNR, PDF)", "url": "https://ccr-zkr.org/files/conventions/cmni_en.pdf"}, {"label": "Conventions overview (CCNR)", "url": "https://www.ccr-zkr.org/13020300-en.html"}]', updated_at=unixepoch() WHERE slug='cmni-budapest-2001';
UPDATE repository_items SET links_json='[{"label": "TIR Handbook 2024 (UNECE, PDF)", "url": "https://unece.org/sites/default/files/2025-01/TIR-6Rev12e_0.pdf"}, {"label": "TIR overview (UNECE)", "url": "https://unece.org/transport/tir"}]', updated_at=unixepoch() WHERE slug='tir-convention-1975';
UPDATE repository_items SET links_json='[{"label": "Regulation (EU) 2020/1056 (EUR-Lex)", "url": "https://eur-lex.europa.eu/eli/reg/2020/1056/oj"}, {"label": "All eFTI acts and timeline (European Commission)", "url": "https://transport.ec.europa.eu/transport-themes/logistics-and-multimodal-transport/efti-regulation_en"}]', updated_at=unixepoch() WHERE slug='efti-regulation-2020-1056';
INSERT INTO repository_items (item_id, title, description, file_key, mime_type, published, access_level,
  external_url, slug, category, cover_image_key, summary_en, summary_nl, summary_de, summary_fr, links_json)
VALUES ('c732b19d-5b89-49e8-b87d-98bb2f03267c', 'eFTI common data set — Delegated Regulation (EU) 2024/2024', 'Defines the common eFTI data set and data subsets: the exact data elements economic operators may share electronically with authorities under the eFTI Regulation.', '', 'application/pdf', 1, 'public',
  'https://eur-lex.europa.eu/legal-content/EN/AUTO/?uri=CELEX:32024R2024', 'efti-delegated-2024-2024', 'regulation', 'marketing/covers/repo-efti-delegated-2024-2024.jpg',
  'Defines the common eFTI data set and data subsets: the exact data elements economic operators may share electronically with authorities under the eFTI Regulation. The technical dictionary that platforms and authorities implement.', 'Definieert de gemeenschappelijke eFTI-gegevensset en -subsets: de exacte gegevenselementen die ondernemers elektronisch met autoriteiten kunnen delen onder de eFTI-verordening. Het technische woordenboek dat platforms en autoriteiten implementeren.', 'Definiert den gemeinsamen eFTI-Datensatz und die Datenteilsätze: die genauen Datenelemente, die Unternehmen elektronisch mit Behörden gemäß der eFTI-Verordnung teilen können. Das technische Wörterbuch für Plattformen und Behörden.', 'Définit le jeu de données commun eFTI et ses sous-ensembles : les éléments de données exacts que les opérateurs peuvent partager électroniquement avec les autorités en vertu du règlement eFTI. Le dictionnaire technique mis en œuvre par les plateformes et les autorités.', '[{"label": "Official source", "url": "https://eur-lex.europa.eu/legal-content/EN/AUTO/?uri=CELEX:32024R2024"}]');
INSERT INTO repository_items (item_id, title, description, file_key, mime_type, published, access_level,
  external_url, slug, category, cover_image_key, summary_en, summary_nl, summary_de, summary_fr, links_json)
VALUES ('616fdc34-d7c1-49c0-b52a-27e1b43878de', 'eFTI Annex I amendment — Delegated Regulation (EU) 2024/2025', 'Updates Annex I Part B of the eFTI Regulation: the list of national requirements on regulatory freight information that member states have notified.', '', 'application/pdf', 1, 'public',
  'https://eur-lex.europa.eu/legal-content/EN/AUTO/?uri=CELEX:32024R2025', 'efti-delegated-2024-2025', 'regulation', 'marketing/covers/repo-efti-delegated-2024-2025.jpg',
  'Updates Annex I Part B of the eFTI Regulation: the list of national requirements on regulatory freight information that member states have notified. Determines which national obligations fall within the eFTI electronic-acceptance regime.', 'Actualiseert Bijlage I deel B van de eFTI-verordening: de lijst van door lidstaten gemelde nationale eisen voor vervoersinformatie. Bepaalt welke nationale verplichtingen onder het elektronische acceptatieregime van eFTI vallen.', 'Aktualisiert Anhang I Teil B der eFTI-Verordnung: die Liste der von den Mitgliedstaaten notifizierten nationalen Anforderungen an Beförderungsinformationen. Legt fest, welche nationalen Pflichten unter das elektronische Akzeptanzregime fallen.', 'Met à jour l''annexe I partie B du règlement eFTI : la liste des exigences nationales notifiées par les États membres concernant les informations de transport. Détermine quelles obligations nationales relèvent du régime d''acceptation électronique eFTI.', '[{"label": "Official source", "url": "https://eur-lex.europa.eu/legal-content/EN/AUTO/?uri=CELEX:32024R2025"}]');
INSERT INTO repository_items (item_id, title, description, file_key, mime_type, published, access_level,
  external_url, slug, category, cover_image_key, summary_en, summary_nl, summary_de, summary_fr, links_json)
VALUES ('51e88bd3-6373-4e3d-9989-aee8971d459e', 'eFTI authority access — Implementing Regulation (EU) 2024/1942', 'Lays down the common procedures and detailed rules for how competent authorities access and process regulatory freight transport information on certified eFTI platforms, including the link with national enforcement systems..', '', 'application/pdf', 1, 'public',
  'https://eur-lex.europa.eu/legal-content/EN/AUTO/?uri=CELEX:32024R1942', 'efti-implementing-2024-1942', 'regulation', 'marketing/covers/repo-efti-implementing-2024-1942.jpg',
  'Lays down the common procedures and detailed rules for how competent authorities access and process regulatory freight transport information on certified eFTI platforms, including the link with national enforcement systems.', 'Legt de gemeenschappelijke procedures en regels vast voor de toegang van bevoegde autoriteiten tot vervoersinformatie op gecertificeerde eFTI-platforms, inclusief de koppeling met nationale handhavingssystemen.', 'Legt die gemeinsamen Verfahren und Regeln fest, nach denen zuständige Behörden auf Beförderungsinformationen auf zertifizierten eFTI-Plattformen zugreifen und sie verarbeiten, einschließlich der Anbindung nationaler Kontrollsysteme.', 'Établit les procédures communes et les règles détaillées d''accès des autorités compétentes aux informations de transport sur les plateformes eFTI certifiées, y compris le lien avec les systèmes nationaux de contrôle.', '[{"label": "Official source", "url": "https://eur-lex.europa.eu/legal-content/EN/AUTO/?uri=CELEX:32024R1942"}]');
INSERT INTO repository_items (item_id, title, description, file_key, mime_type, published, access_level,
  external_url, slug, category, cover_image_key, summary_en, summary_nl, summary_de, summary_fr, links_json)
VALUES ('cde2b3f9-cbc9-4ff7-8edd-1b0996ef8bd7', 'eFTI platform requirements — Implementing Regulation (EU) 2025/2243', 'Sets the detailed functional requirements that eFTI platforms and eFTI service providers must meet for certification: data security, processing, authentication and interoperability.', '', 'application/pdf', 1, 'public',
  'https://eur-lex.europa.eu/legal-content/en/AUTO/?uri=CELEX:32025R2243', 'efti-implementing-2025-2243', 'regulation', 'marketing/covers/repo-efti-implementing-2025-2243.jpg',
  'Sets the detailed functional requirements that eFTI platforms and eFTI service providers must meet for certification: data security, processing, authentication and interoperability. The compliance benchmark for every platform on the market.', 'Bevat de gedetailleerde functionele eisen waaraan eFTI-platforms en -dienstverleners moeten voldoen voor certificering: gegevensbeveiliging, verwerking, authenticatie en interoperabiliteit. De maatstaf voor elk platform op de markt.', 'Enthält die detaillierten funktionalen Anforderungen, die eFTI-Plattformen und -Dienstleister für die Zertifizierung erfüllen müssen: Datensicherheit, Verarbeitung, Authentifizierung und Interoperabilität. Der Maßstab für jede Plattform am Markt.', 'Fixe les exigences fonctionnelles détaillées que les plateformes et prestataires eFTI doivent respecter pour la certification : sécurité des données, traitement, authentification et interopérabilité. La référence de conformité pour chaque plateforme.', '[{"label": "Official source", "url": "https://eur-lex.europa.eu/legal-content/en/AUTO/?uri=CELEX:32025R2243"}]');
INSERT INTO repository_items (item_id, title, description, file_key, mime_type, published, access_level,
  external_url, slug, category, cover_image_key, summary_en, summary_nl, summary_de, summary_fr, links_json)
VALUES ('1ce59415-ad53-471a-a1f3-ab815ec893ef', 'Driving and rest times — Regulation (EC) 561/2006', 'The core EU rules on driving times, breaks and rest periods for professional drivers, extended by the Mobility Package.', '', 'application/pdf', 1, 'public',
  'https://eur-lex.europa.eu/legal-content/EN/AUTO/?uri=CELEX:32006R0561', 'reg-561-2006-driving-rest', 'regulation', 'marketing/covers/repo-reg-561-2006-driving-rest.jpg',
  'The core EU rules on driving times, breaks and rest periods for professional drivers, extended by the Mobility Package. The basis for tachograph enforcement across the EU.', 'De kern van de EU-regels voor rijtijden, pauzes en rusttijden van beroepschauffeurs, uitgebreid door het Mobility Package. De basis voor tachograafhandhaving in de hele EU.', 'Die zentralen EU-Vorschriften über Lenkzeiten, Fahrtunterbrechungen und Ruhezeiten für Berufskraftfahrer, erweitert durch das Mobilitätspaket. Grundlage der Tachographen-Durchsetzung in der EU.', 'Les règles fondamentales de l''UE sur les temps de conduite, les pauses et les temps de repos des conducteurs professionnels, étendues par le paquet mobilité. La base du contrôle par tachygraphe dans l''UE.', '[{"label": "Official source", "url": "https://eur-lex.europa.eu/legal-content/EN/AUTO/?uri=CELEX:32006R0561"}]');
INSERT INTO repository_items (item_id, title, description, file_key, mime_type, published, access_level,
  external_url, slug, category, cover_image_key, summary_en, summary_nl, summary_de, summary_fr, links_json)
VALUES ('30e765ee-e577-4fba-9c67-3586c28c248d', 'Tachographs — Regulation (EU) 165/2014', 'Governs the construction, installation, use and inspection of tachographs in road transport, including the smart tachograph generations used to enforce driving-time and posting rules across borders..', '', 'application/pdf', 1, 'public',
  'https://eur-lex.europa.eu/legal-content/EN/AUTO/?uri=CELEX:32014R0165', 'reg-165-2014-tachographs', 'regulation', 'marketing/covers/repo-reg-165-2014-tachographs.jpg',
  'Governs the construction, installation, use and inspection of tachographs in road transport, including the smart tachograph generations used to enforce driving-time and posting rules across borders.', 'Regelt de bouw, installatie, het gebruik en de controle van tachografen in het wegvervoer, inclusief de generaties slimme tachograaf waarmee rijtijden- en detacheringsregels grensoverschrijdend worden gehandhaafd.', 'Regelt Bau, Einbau, Benutzung und Prüfung von Fahrtenschreibern im Straßenverkehr, einschließlich der Generationen des intelligenten Fahrtenschreibers zur grenzüberschreitenden Durchsetzung von Lenkzeit- und Entsenderegeln.', 'Régit la construction, l''installation, l''utilisation et le contrôle des tachygraphes dans le transport routier, y compris les générations de tachygraphe intelligent utilisées pour faire respecter les temps de conduite et les règles de détachement.', '[{"label": "Official source", "url": "https://eur-lex.europa.eu/legal-content/EN/AUTO/?uri=CELEX:32014R0165"}, {"label": "Smart Tachograph enforcement and retrofit phases (European Commission)", "url": "https://transport.ec.europa.eu/news-events/news/stronger-and-more-unified-enforcement-eu-rules-international-road-transport-smart-tachograph-2025-08-19_en"}]');
INSERT INTO repository_items (item_id, title, description, file_key, mime_type, published, access_level,
  external_url, slug, category, cover_image_key, summary_en, summary_nl, summary_de, summary_fr, links_json)
VALUES ('371079a4-e79f-45a1-a4e5-3888e6cdcb7c', 'Mobility Package I: driving, rest and tachograph — Regulation (EU) 2020/1054', 'Amends the driving-and-rest-time rules and accelerates the smart tachograph roll-out: return of the driver, ban on regular weekly rest in the cab, and retrofit deadlines for international transport..', '', 'application/pdf', 1, 'public',
  'https://eur-lex.europa.eu/legal-content/EN/AUTO/?uri=CELEX:32020R1054', 'reg-2020-1054-mobility-package', 'regulation', 'marketing/covers/repo-reg-2020-1054-mobility-package.jpg',
  'Amends the driving-and-rest-time rules and accelerates the smart tachograph roll-out: return of the driver, ban on regular weekly rest in the cab, and retrofit deadlines for international transport.', 'Wijzigt de rij- en rusttijdenregels en versnelt de uitrol van de slimme tachograaf: terugkeer van de chauffeur, verbod op normale weekendrust in de cabine en retrofit-deadlines voor internationaal vervoer.', 'Ändert die Lenk- und Ruhezeitregeln und beschleunigt die Einführung des intelligenten Fahrtenschreibers: Rückkehr des Fahrers, Verbot der regelmäßigen wöchentlichen Ruhezeit in der Kabine und Nachrüstfristen im internationalen Verkehr.', 'Modifie les règles de conduite et de repos et accélère le déploiement du tachygraphe intelligent : retour du conducteur, interdiction du repos hebdomadaire normal en cabine et échéances de mise à niveau pour le transport international.', '[{"label": "Official source", "url": "https://eur-lex.europa.eu/legal-content/EN/AUTO/?uri=CELEX:32020R1054"}]');
INSERT INTO repository_items (item_id, title, description, file_key, mime_type, published, access_level,
  external_url, slug, category, cover_image_key, summary_en, summary_nl, summary_de, summary_fr, links_json)
VALUES ('8e79441f-49f0-42c6-820d-2b63a543695c', 'Mobility Package I: establishment and cabotage — Regulation (EU) 2020/1055', 'Tightens access to the road transport market: real establishment requirements, the return of the vehicle every eight weeks, and the cabotage cooling-off period.', '', 'application/pdf', 1, 'public',
  'https://eur-lex.europa.eu/legal-content/EN/AUTO/?uri=CELEX:32020R1055', 'reg-2020-1055-establishment-cabotage', 'regulation', 'marketing/covers/repo-reg-2020-1055-establishment-cabotage.jpg',
  'Tightens access to the road transport market: real establishment requirements, the return of the vehicle every eight weeks, and the cabotage cooling-off period. Aimed at letterbox companies and systematic cabotage.', 'Verscherpt de toegang tot de wegvervoermarkt: eisen aan echte vestiging, terugkeer van het voertuig elke acht weken en de afkoelperiode voor cabotage. Gericht tegen brievenbusfirma''s en systematische cabotage.', 'Verschärft den Zugang zum Güterkraftverkehrsmarkt: Anforderungen an eine tatsächliche Niederlassung, Rückkehr des Fahrzeugs alle acht Wochen und Karenzzeit bei Kabotage. Gegen Briefkastenfirmen und systematische Kabotage.', 'Durcit l''accès au marché du transport routier : exigences d''établissement réel, retour du véhicule toutes les huit semaines et délai de carence pour le cabotage. Vise les sociétés boîtes aux lettres et le cabotage systématique.', '[{"label": "Official source", "url": "https://eur-lex.europa.eu/legal-content/EN/AUTO/?uri=CELEX:32020R1055"}]');
INSERT INTO repository_items (item_id, title, description, file_key, mime_type, published, access_level,
  external_url, slug, category, cover_image_key, summary_en, summary_nl, summary_de, summary_fr, links_json)
VALUES ('2cdf6dc1-1f19-4f9c-a318-d7f497ac4399', 'AETR Agreement — driving and rest times beyond the EU', 'The UNECE agreement applying driving-time, break and rest-period rules to international road transport between the EU and non-EU countries such as the UK, Türkiye and the EAEU states.', '', 'application/pdf', 1, 'public',
  'https://unece.org/transport/road-transport/aetr', 'aetr-agreement', 'convention', 'marketing/covers/repo-aetr-agreement.jpg',
  'The UNECE agreement applying driving-time, break and rest-period rules to international road transport between the EU and non-EU countries such as the UK, Türkiye and the EAEU states. Follows the EU regime closely, including tachograph requirements.', 'De UNECE-overeenkomst die rijtijden-, pauze- en rusttijdenregels toepast op internationaal wegvervoer tussen de EU en niet-EU-landen zoals het VK, Turkije en de EAEU-staten. Volgt het EU-regime op de voet, inclusief tachograafeisen.', 'Das UNECE-Übereinkommen, das Lenkzeit-, Pausen- und Ruhezeitregeln auf den internationalen Straßenverkehr zwischen der EU und Nicht-EU-Staaten wie dem Vereinigten Königreich, der Türkei und den EAWU-Staaten anwendet. Folgt eng dem EU-Regime, einschließlich Tachographenpflichten.', 'L''accord de la CEE-ONU appliquant les règles de temps de conduite, de pause et de repos au transport routier international entre l''UE et des pays tiers comme le Royaume-Uni, la Türkiye et les États de l''UEEA. Suit de près le régime de l''UE, y compris le tachygraphe.', '[{"label": "Official source", "url": "https://unece.org/transport/road-transport/aetr"}]');
INSERT INTO repository_items (item_id, title, description, file_key, mime_type, published, access_level,
  external_url, slug, category, cover_image_key, summary_en, summary_nl, summary_de, summary_fr, links_json)
VALUES ('1cee495f-60b6-4400-acdd-922c4364d847', 'ADR 2025 — carriage of dangerous goods by road', 'The UNECE agreement governing the international carriage of dangerous goods by road: classification, packaging, labelling, vehicle and driver requirements.', '', 'application/pdf', 1, 'public',
  'https://unece.org/transport/dangerous-goods/adr-2025-files', 'adr-2025-dangerous-goods', 'convention', 'marketing/covers/repo-adr-2025-dangerous-goods.jpg',
  'The UNECE agreement governing the international carriage of dangerous goods by road: classification, packaging, labelling, vehicle and driver requirements. The 2025 edition files are the currently applicable texts.', 'De UNECE-overeenkomst voor internationaal vervoer van gevaarlijke stoffen over de weg: classificatie, verpakking, etikettering, voertuig- en chauffeurseisen. De 2025-editie bevat de nu geldende teksten.', 'Das UNECE-Übereinkommen über die internationale Beförderung gefährlicher Güter auf der Straße: Klassifizierung, Verpackung, Kennzeichnung, Fahrzeug- und Fahreranforderungen. Die Ausgabe 2025 enthält die aktuell geltenden Texte.', 'L''accord de la CEE-ONU régissant le transport international de marchandises dangereuses par route : classification, emballage, étiquetage, exigences pour les véhicules et les conducteurs. L''édition 2025 constitue les textes applicables.', '[{"label": "Official source", "url": "https://unece.org/transport/dangerous-goods/adr-2025-files"}]');
INSERT INTO repository_items (item_id, title, description, file_key, mime_type, published, access_level,
  external_url, slug, category, cover_image_key, summary_en, summary_nl, summary_de, summary_fr, links_json)
VALUES ('c1213186-ef80-4ffc-b5d8-d03649303721', 'Rotterdam Rules — carriage of goods by sea', 'The UNCITRAL convention on contracts for international carriage of goods wholly or partly by sea, designed to modernise the Hague-Visby and Hamburg regimes, with rules for door-to-door transport and electronic transport records.', '', 'application/pdf', 1, 'public',
  'https://uncitral.un.org/en/texts/transportgoods/conventions/rotterdam_rules', 'rotterdam-rules', 'convention', 'marketing/covers/repo-rotterdam-rules.jpg',
  'The UNCITRAL convention on contracts for international carriage of goods wholly or partly by sea, designed to modernise the Hague-Visby and Hamburg regimes, with rules for door-to-door transport and electronic transport records. Not yet widely in force.', 'Het UNCITRAL-verdrag over overeenkomsten voor internationaal goederenvervoer geheel of gedeeltelijk over zee, bedoeld om de Hague-Visby- en Hamburg-regimes te moderniseren, met regels voor deur-tot-deurvervoer en elektronische vervoersdocumenten. Nog niet breed in werking.', 'Das UNCITRAL-Übereinkommen über Verträge über die internationale Güterbeförderung ganz oder teilweise auf See, zur Modernisierung der Haag-Visby- und Hamburg-Regime, mit Regeln für Haus-zu-Haus-Transporte und elektronische Beförderungsdokumente. Noch nicht breit in Kraft.', 'La convention de la CNUDCI sur le transport international de marchandises effectué entièrement ou partiellement par mer, destinée à moderniser les régimes de La Haye-Visby et de Hambourg, avec des règles pour le porte-à-porte et les documents électroniques. Pas encore largement en vigueur.', '[{"label": "Official source", "url": "https://uncitral.un.org/en/texts/transportgoods/conventions/rotterdam_rules"}]');
INSERT INTO repository_items (item_id, title, description, file_key, mime_type, published, access_level,
  external_url, slug, category, cover_image_key, summary_en, summary_nl, summary_de, summary_fr, links_json)
VALUES ('f3b1592a-0fb9-4b9b-a247-a3e93b79988d', 'UN transport legal instruments — full list (UNECE)', 'The UNECE index of all United Nations transport legal instruments: conventions and agreements on road, rail, inland waterway, dangerous goods, vehicles and border crossing.', '', 'application/pdf', 1, 'public',
  'https://unece.org/transport/list-united-nations-transport-legal-instruments', 'un-transport-legal-instruments', 'reference', 'marketing/covers/repo-un-transport-legal-instruments.jpg',
  'The UNECE index of all United Nations transport legal instruments: conventions and agreements on road, rail, inland waterway, dangerous goods, vehicles and border crossing. The starting point for finding any instrument''s status and text.', 'De UNECE-index van alle VN-vervoersrechtsinstrumenten: verdragen en overeenkomsten over weg, spoor, binnenvaart, gevaarlijke stoffen, voertuigen en grenspassage. Het startpunt om de status en tekst van elk instrument te vinden.', 'Der UNECE-Index aller Rechtsinstrumente der Vereinten Nationen im Verkehr: Übereinkommen über Straße, Schiene, Binnenschifffahrt, Gefahrgut, Fahrzeuge und Grenzübertritt. Der Ausgangspunkt für Status und Text jedes Instruments.', 'L''index de la CEE-ONU de tous les instruments juridiques des Nations Unies en matière de transport : conventions sur la route, le rail, la navigation intérieure, les marchandises dangereuses, les véhicules et le passage des frontières. Le point de départ pour trouver le statut et le texte de chaque instrument.', '[{"label": "Official source", "url": "https://unece.org/transport/list-united-nations-transport-legal-instruments"}]');
